### ISSUE TITLE
Not working with react-refresh 0.12.0

### ISSUE THREAD

**Issue by Jack-Works** [pmmmwh/react-refresh-webpack-plugin#619]
```js
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime.js' is not defined by "exports" in react-refresh/package.json
```

![image](https://user-images.githubusercontent.com/5390719/160759814-17a8a326-95fa-4236-bee4-ba3cc215c466.png)

**Comment by pierrecholhot** [comment]
In my setup this error started showing after upgrading `react-scripts` to 5.0.0.

Taken from TROUBLESHOOTING.md, I was able to circumvent it using:

```shell
npm install --legacy-peer-deps
```

node v16.9.1 – npm v7.21.1 – react-scripts v5.0.0

**Comment by ntucker** [comment]
This is fixed in https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/565 but we are all waiting on a version with this fix to be published.

**Comment by kimbaudi** [comment]
I also got the following error:

```
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime.js' is not defined by "exports" in react-refresh-error\node_modules\react-refresh\package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (react-refresh-error\node_modules\@pmmmwh\react-refresh-webpack-plugin\loader\index.js:20:4)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

ERROR in ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js 4:23-58
Module not found: Error: Package path ./runtime.js is not exported from package eact-refresh-error\node_modules\react-refresh (see exports field in react-refresh-error\node_modules\react-refresh\package.json)
```

looking forward to the next release w/ the fix 🙏 😄

**Comment by luckymore** [comment]
> This is fixed in #576 but we are all waiting on a version with this fix to be published.

still get the same error 😭
<img width="860" alt="image" src="https://user-images.githubusercontent.com/5390013/161368318-f2976a9e-5108-4e6f-a30a-500ad5eaaf96.png">

**Comment by pmmmwh** [comment]
Released in 0.5.5
